module AuthSanitizer
  module Loader
    FILES: Array[String]

    def self.load_isolated: () -> Module
  end
end

module Auth
  module Sanitizer
    module Version
      VERSION: String
    end
    VERSION: String
  end
end
