module Auth
  module Sanitizer
    VERSION: String
    # See the writing guide of rbs: https://github.com/ruby/rbs#guides
  end
end

module AuthSanitizer
  module Loader
    FILES: Array[String]

    def self.load_isolated: () -> Module
  end
end
